import Head from 'next/head'
import TopNav from '../components/TopNav'
import { Box, Container, Stack, HStack, VStack, Heading, Text, Icon, Button, SimpleGrid, Select } from '@chakra-ui/react'
import CartItem from '../components/CartItem'
import CheckoutBox from '../components/CheckoutBox'
import { useAppSelector } from '../hooks'

export default function Cart() {
  const productsInCart = Object.values(useAppSelector(state => state.cart.products));

  return (
    <main>
      <Head>
        <title>Mon Chocolat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopNav />

      <Container 
        maxW={{
          base: 'container.md',
          lg: 'container.lg',
          xl: 'container.xl'
        }}
        mt="12"
        mb="6"
      >
        <Heading as="h1">Panier</Heading>
      </Container>

      <Container 
        maxW={{
          base: 'container.md',
          lg: 'container.lg',
          xl: 'container.xl'
        }}
      >
        <Stack
          direction={{
            base: 'column',
            lg: 'row'
          }}
          spacing="8"
        >
          <VStack 
            w="100%"
            spacing="4"
          >
            {productsInCart.map(product => (
              <CartItem key={product.id} {...product}/>
            ))}
          </VStack>

          
          <CheckoutBox 
            products={productsInCart} 
            shipping={{
              name: 'Standard (3 jours ouvrables)',
              price: 9.99
            }}
          />
        </Stack>
 
      </Container>

 
    </main>
  )
}