import React from 'react';
import Head from 'next/head'
import { Box, Container, HStack, VStack, Heading, Text, Icon, Button, SimpleGrid, Select } from '@chakra-ui/react';
import { FaCartPlus } from 'react-icons/fa';
import TopNav from '../components/TopNav';
import { useQuery } from 'react-query';

interface Product {
  id: number;
  name: string;
  price: number;
}

export default function Home() {
  const { data: products } = useQuery<Product[]>('products', async () => {
    const response = await fetch('./api/products');
    const data = await response.json();

    return data.products;
  });

  return (
    <main>
      <Head>
        <title>Mon Chocolat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopNav />

      <Container 
        maxW={{
          base: 'container.md',
          lg: 'container.lg',
          xl: 'container.xl'
        }}
        mt="12"
        mb="6"
      >
        <HStack justify="space-between">
          <Heading as="h1">Store</Heading>
          <Select
            bg="gray.300"
            color="black"
            maxW={{
              base: "200px",
              lg: "300px"
            }}
          >
            <option value="">Default sorting</option>
            <option value="">Prix (descendant)</option>
            <option value="">Prix (ascendant)</option>
          </Select>
        </HStack>
      </Container>

      <Container 
        maxW={{
          base: 'container.md',
          lg: 'container.lg',
          xl: 'container.xl'
        }}
        py="4"
      >
        <SimpleGrid minChildWidth="300px" gap="40px" maxW="992px" mx="auto">
          {products && products.map(({id, name, price}) => (
            <VStack
              key={id}
              bg="gray.400"
              p="8"
              color="black"
              pos="relative"
              borderRadius="32px"
            >
              <HStack w="100%">
                <Button
                  p="2"
                  as="a"
                  ml="auto"
                  bg="transparent"
                  border="1px"
                  borderColor="gray.500"
                  borderRadius="100%"
                  cursor="pointer"
                >
                  <Icon as={FaCartPlus} fontSize="md"/>
                </Button>
              </HStack>

              <Box w="100px" h="200px" bg="gray.700"></Box>

              <VStack spacing="0">
                <Text mt="8" fontSize="larger" fontWeight="bold" letterSpacing="3px">{name}</Text>
                <Text>${price}</Text>
              </VStack>
            </VStack>
          ))}
        </SimpleGrid>
      </Container>
    </main>
  )
}