import Head from 'next/head'

export default function Cart() {
  return (
    <main>
      <Head>
        <title>Mon Chocolat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </main>
  )
}