import React from 'react';
import Head from 'next/head'
import Link from 'next/link'
import { Box, Container, HStack, Heading, Text, Icon, Button } from '@chakra-ui/react';
import { FaShoppingCart } from 'react-icons/fa';

export default function Home() {
  return (
    <main>
      <Head>
        <title>Mon Chocolat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box bg="gray.700" as="nav">
        <Container 
          maxW={{
            base: 'container.md',
            lg: 'container.lg',
            xl: 'container.xl'
          }}
          py="4"
        >
          <HStack justify="space-between">
            <Heading
              fontSize="2xl"
            >
              mon chocolat
            </Heading>
            <Link href="/cart" passHref>
              <Button
                p="2"
                as="a"
                bg="transparent"
                _hover={{
                  bg: "gray.500"
                }}
                borderRadius="100%"
              >
                <Icon as={FaShoppingCart} fontSize="xl"/>
              </Button>
            </Link>
          </HStack>
        </Container>
      </Box>

      
    </main>
  )
}
